# Generated by Django 5.1.3 on 2024-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
